# render.yaml

services:
  - name: youtube-live-streaming
    type: worker
    buildCommand: npm install
    startCommand: node main.js
    env:
      - key: STREAM_KEY
        from: secret
        name: streamkey
    # Add other necessary configurations

secrets:
  - name: streamkey
    value: "FB-234939859616247-0-AbxDDYjxMGNfyRt-"
